### ISSUE TITLE
Failure in TestHTTPSClientAuth 

### ISSUE THREAD

**Issue by nischalsheth** [mailgun/gubernator#100]
Seen with the latest code (using go 1.16.6).

nsheth-mbp:gubernator[86505]git remote -vv
origin  https://github.com/mailgun/gubernator.git (fetch)
origin  https://github.com/mailgun/gubernator.git (push)
nsheth-mbp:gubernator[86506]git branch
\* master
nsheth-mbp:gubernator[86507]git log -n1
commit fa69d958159cd9e1152a18719759c147326087af (HEAD -> master, tag: v2.0.0-rc.2, origin/master, origin/HEAD)
Merge: cc98f3a 92b79a8
Author: Maxim Vladimirskiy <horkhe@gmail.com>
Date:   Mon Jul 5 11:07:27 2021 +0300

    Merge pull request #96 from mailgun/maxim/develop
    
    PIP-1319: Use the latest protobuf

nsheth-mbp:gubernator[86508]go test -v -vet off -run TestHTTPSClientAuth
INFO[0000] GRPC Listening on 127.0.0.1:9990 ...          instance="127.0.0.1:9990"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9980 ...  instance="127.0.0.1:9990"
INFO[0000] GRPC Listening on 127.0.0.1:9991 ...          instance="127.0.0.1:9991"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9981 ...  instance="127.0.0.1:9991"
INFO[0000] GRPC Listening on 127.0.0.1:9992 ...          instance="127.0.0.1:9992"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9982 ...  instance="127.0.0.1:9992"
INFO[0000] GRPC Listening on 127.0.0.1:9993 ...          instance="127.0.0.1:9993"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9983 ...  instance="127.0.0.1:9993"
INFO[0000] GRPC Listening on 127.0.0.1:9994 ...          instance="127.0.0.1:9994"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9984 ...  instance="127.0.0.1:9994"
INFO[0000] GRPC Listening on 127.0.0.1:9995 ...          instance="127.0.0.1:9995"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9985 ...  instance="127.0.0.1:9995"
INFO[0000] GRPC Listening on 127.0.0.1:9890 ...          instance="127.0.0.1:9890"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9880 ...  instance="127.0.0.1:9890"
INFO[0000] GRPC Listening on 127.0.0.1:9891 ...          instance="127.0.0.1:9891"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9881 ...  instance="127.0.0.1:9891"
INFO[0000] GRPC Listening on 127.0.0.1:9892 ...          instance="127.0.0.1:9892"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9882 ...  instance="127.0.0.1:9892"
INFO[0000] GRPC Listening on 127.0.0.1:9893 ...          instance="127.0.0.1:9893"
INFO[0000] HTTP Gateway Listening on 127.0.0.1:9883 ...  instance="127.0.0.1:9893"
=== RUN   TestHTTPSClientAuth
INFO[0000] Detected TLS Configuration                    category=gubernator
INFO[0000] GRPC Listening on 127.0.0.1:9695 ...          category=gubernator
INFO[0000] GRPC Gateway Listening on 127.0.0.1:52208 ...  category=gubernator
INFO[0000] HTTPS Gateway Listening on 127.0.0.1:9685 ...  category=gubernator
INFO[0000] http: TLS handshake error from 127.0.0.1:52209: EOF  category=gubernator
    tls_test.go:289: 
                Error Trace:    tls_test.go:289
                Error:          Not equal: 
                                expected: "{\"status\":\"healthy\",\"message\":\"\",\"peerCount\":0}"
                                actual  : "{\"status\":\"healthy\", \"message\":\"\", \"peerCount\":0}"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -{"status":"healthy","message":"","peerCount":0}
                                +{"status":"healthy", "message":"", "peerCount":0}
                Test:           TestHTTPSClientAuth
INFO[0000] HTTP Gateway close for 127.0.0.1:9685 ...     category=gubernator
INFO[0000] GRPC close for 127.0.0.1:9695 ...             category=gubernator
INFO[0000] GRPC close for 127.0.0.1:52208 ...            category=gubernator
--- FAIL: TestHTTPSClientAuth (0.17s)
FAIL
exit status 1
FAIL    github.com/mailgun/gubernator/v2        0.573s

nsheth-mbp:gubernator[86510]go version
go version go1.16.6 darwin/amd64

nsheth-mbp:gubernator[86511]uname -a
Darwin nsheth-mbp.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

All tests pass with the following change:

```
diff --git a/tls_test.go b/tls_test.go
index e9af60f..4a485dd 100644
--- a/tls_test.go
+++ b/tls_test.go
@@ -286,5 +286,5 @@ func TestHTTPSClientAuth(t *testing.T) {
        require.NoError(t, err)
        b, err := ioutil.ReadAll(resp.Body)
        require.NoError(t, err)
-       assert.Equal(t, `{"status":"healthy","message":"","peerCount":0}`, string(b))
+       assert.Equal(t, `{"status":"healthy", "message":"", "peerCount":0}`, string(b))
 }
```

**Comment by thrawn01** [comment]
Thank you for reporting this! Fixed in #103
