### ISSUE TITLE
peerCount: 0 in a healthy cluster

### ISSUE THREAD

**Issue by dimaqq** [mailgun/gubernator#101]
In two kinds of deployments:
* `etcd`
* my custom #99 

I'm seeing that gubernator instances are clearly talking to each other (`remaining` is decreased on peer nodes), and yet the health check returns `{"status":"healthy","message":"","peerCount":0}`

**Comment by dimaqq** [comment]
it appears that peer count is only populated if there are errors:

https://github.com/mailgun/gubernator/blob/72b954141ed27619433b103c42657f4470e96b39/gubernator.go#L362-L365

**Comment by thrawn01** [comment]
Fixed in #105
