### ISSUE TITLE
JSON response spelling

### ISSUE THREAD

**Issue by dimaqq** [mailgun/gubernator#104]
While working on #99 I made a `gubernator` docker image via:
* `git clone`
* `make docker`

This image produces response JSON in a slightly different format than documented:

```
{
  responses: [
  {
    error: '', 
    limit: '100', 
    metadata: {"owner":"'10.125.2.248:81'"}, 
    remaining: '99', 
    resetTime: '1628846037905', 
    status: 'UNDER_LIMIT'
  }
  ]
}
```

There appears to be exactly 1 difference vs. `gubernator` from docker hub:
`reset_time` became `resetTime` (snake_case to camelCase).

I'm not sure why... I guess it's the gRPC magic?

(unrelated: README.md top-level key is `rate_limits` in the GRPS sample, but `responses` in the JSON sample 🤷🏿  )

**Comment by dimaqq** [comment]
https://github.com/golang/protobuf/issues/193 maybe?

**Comment by thrawn01** [comment]
This was a fun one, turns our GRPC-Gateway prefers `camelCase` when marshaling JSON responses even though the `json` tag is in `under_score`.  (See https://github.com/grpc-ecosystem/grpc-gateway/issues/1426) 

You have to override the default marshal with `runtime.WithMarshalerOption()`.

See #105
