### ISSUE TITLE
Cannot upgrade gubernator?

### ISSUE THREAD

**Issue by miparnisari** [mailgun/gubernator#134]
In my package i'm trying to update `gubernator` from `2.0.0-rc10` to `2.0.0-rc15`:

![image](https://user-images.githubusercontent.com/5374887/158906299-064f598e-5ab3-4819-a0c8-344f651af924.png)

![image](https://user-images.githubusercontent.com/5374887/158906930-beb5c3f4-2a32-453e-adec-650631b8c09d.png)

However, this breaks my build:

```go
Error: vendor/k8s.io/client-go/discovery/discovery_client.go:32:2: cannot find package "." in:
	/home/runner/work/sandcastle/sandcastle/vendor/github.com/googleapis/gnostic/openapiv2
make[1]: *** [Makefile:156: test-customers-functional] Error 1
```

It looks like it can't find `googleapis/gnostic`? So I tried adding this inside `go.mod`:

```go
replace github.com/googleapis/gnostic => github.com/google/gnostic v0.5.5
```

but this doesn't seem to have any effect. :(

**Comment by denkyl08** [comment]
What version of golang? It looks like you're using vendoring, do you see any files in `vendor/github.com/googleapis/gnostic/openapiv2`? perhaps you need to re-run `go mod vendor`.
