### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by matheus-meneses** [mailgun/gubernator#151]
Hi Guys, any plans to build in arm64 archicteture?

**Comment by thrawn01** [comment]
Good point, we need an arm64 build for docker! PR would be welcome! (If I don't get to it)

**Comment by thrawn01** [comment]
We already build images for `amd` and `arm`. Let me know if this is in error or you are requesting something else not already covered. https://github.com/mailgun/gubernator/blob/d10e8aaa66cd26e5f44a7ee997a2130eaf542923/.github/workflows/on-release.yml#L43
