### ISSUE TITLE
negative hits is not processed when remaining equals 0

### ISSUE THREAD

**Issue by Loosetooth** [mailgun/gubernator#156]
Setting negative `hits` values does not work when `remaining` is already at 0.

In our use-case, we sometimes set the `hits` property in the rate limit request to negative values.
This works well by default, for example, let us suppose that we have the following request, with the current value of `remaining` being 5:
```json
{
    "requests":[
        {
            "name": "requests_per_sec",
            "unique_key": "account.id=1234",
            "hits": -1,
            "duration": 60000,
            "limit": 10
        }
    ]
}
```

This results in the `remaining` increasing by one as expected:
```json
{
  "responses":[
    {
      "status": "UNDER_LIMIT",
      "limit": "10",
      "remaining": "6",
      "reset_time": "1551309219226"
    }
  ]
}
```

However, if the request is done when the value of `remaining` is 0, the negative `hits` do not get processed. The response always returns `'OVER_LIMIT'`, even though we are trying to increase the `remaining` tokens by specifying a negative value.

In case of the `tokenBucket` algorithm for example, the culprit can be found here:
https://github.com/mailgun/gubernator/blob/1803ac23f4a6b5f0028e2dff6c8a34069344f181/algorithms.go#L179-L185

The fix would be relatively straightforward:
```golang
// If we are already at the limit.
if rl.Remaining == 0 && r.Hits > 0 {
	span.AddEvent("Already over the limit")
	overLimitCounter.Add(1)
	rl.Status = Status_OVER_LIMIT
	t.Status = rl.Status
	return rl, nil
}
```

I will try to make a pull request with the fix for the various algorithms.

**Comment by Baliedge** [comment]
Sending negative hits is not a common use case for us, but I can see this being useful.  Good catch!
