### ISSUE TITLE
Using Gubernator as a library 

### ISSUE THREAD

**Issue by yashmehta1** [mailgun/gubernator#163]
Hi team , 

I have some doubts on how to use gubernator as a library. Can you please help me with these ?
- Does using this library means that it is an in memory storage which will handle rate limits or we will have to call an instance in backend using the interface provided in gubernator library?
- I was using this library in my golang service ( version 1.18 ) but whenever I try to build my service after importing this line in any file `"github.com/mailgun/gubernator/v2"` 

I get this error :
```
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig
# go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig
../../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.9.0/internal/otlpconfig/envconfig.go:85:13: undefined: envconfig.WithTLSConfig
../../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.9.0/internal/otlpconfig/envconfig.go:86:13: undefined: envconfig.WithTLSConfig
```

I use this cmd to install gubernator/v2 package `go mod tidy -go=1.18`
I use this cmd to run my service `go build -v -o app main.go`

As 1.9.0 version of otel exporters is required in gubernator.

Can you please help me, as what am I doing wrong ?
Any help will be appreciated

**Comment by thrawn01** [comment]
> Does using this library means that it is an in memory storage which will handle rate limits or we will have to call an instance in backend using the interface provided in gubernator library?
Yes

I'm not sure about that error, but I suspect it has something todo with your dependencies. I'm sorry I can't help you.
