### ISSUE TITLE
Question: Difference between name and unique_key

### ISSUE THREAD

**Issue by Dreamsorcerer** [mailgun/gubernator#174]
I've read through the documentation a couple of times, and I just can't understand what the difference is between a name and a unique_key.

From the documentation, it seems like the rate limit is cached for the combined name+unique_key.

So, for example, the documentation gives this sample:
```
            "name": "requests_per_sec",
            "unique_key": "account.id=1234",
```

But, how does this behave differently from something like:
```
            "name": "requests_per_sec:account.id=1234",
            "unique_key": "",
```

I'm struggling to understand if there's a real purpose to unique_key or not..

**Comment by Dreamsorcerer** [comment]
OK, but when you say the name describes the rate limit definition, there is nothing in Gubernator that enforces that? i.e. You could create totally different rate limits with the same name, but different keys. So, it's purely convention?

**Comment by Baliedge** [comment]
Correct.  The convention could be more useful outside of Gubernator.  For example, internally we use Gubernator with a wrapper service that has persistent storage for rate limit definitions based on name.  Any newly used keys to `GetRateLimits` endpoint will replicate the default rate limit definition for that name.  This way, we can easily define a default rate limit and also per-account customized rate limits.

**Comment by Dreamsorcerer** [comment]
I guess it depends if Go or other languages are a little more fiddly, but if I was designing it for Python only, I'd just handle it all on the Python side (e.g. using name/key in Python and then doing `name=f"{name}:{key}"`) and reduce the amount of API variables. That's why I was checking that I wasn't misunderstanding something.
