### ISSUE TITLE
Please upgrade go.opentelemetry.io/* dependencies

### ISSUE THREAD

**Issue by pbennett** [mailgun/gubernator#183]
These are reasonably common dependencies across multiple packages and types moved recently sometime between otel 1.13 and 1.16.
Updating the trio of dependencies should be sufficient.

**Comment by thrawn01** [comment]
Pull requests are welcome. I think this should easy an easy update.

**Comment by Baliedge** [comment]
Changes released in v2.0.0-rc.49.
