### ISSUE TITLE
Adding rate_limit_name as tag on metrics

### ISSUE THREAD

**Issue by bjoernw** [mailgun/gubernator#191]
Right now I'm collecting data about individual rate limits on the client side but it would be nice if I didn't have to add this to every client across languages. Being able to stratify the metrics by rate limit name would be useful.

Mostly thinking about these:
```
var metricCheckCounter = prometheus.NewCounter(prometheus.CounterOpts{
	Name: "gubernator_check_counter",
	Help: "The number of rate limits checked.",
})
var metricOverLimitCounter = prometheus.NewCounter(prometheus.CounterOpts{
	Name: "gubernator_over_limit_counter",
	Help: "The number of rate limit checks that are over the limit.",
})
```

Happy to work on this

**Comment by bjoernw** [comment]
@thrawn01 any objections?

**Comment by Baliedge** [comment]
I recommend against this because the cardinality of rate limit names is unlimited.  Instead, your suggested alternative is correct to create a metric around your client-side call to Gubernator.

**Comment by thrawn01** [comment]
The proposal doesn't include the name, just a counter of checks and how many were over the limit. I don't see an issue with that at all. If the metric did include the name of the rate limit that would quickly break Prometheus.

If it's just a counter of checks and over limits it should be fine!

**Comment by Baliedge** [comment]
My apologies, I misread the intentions.
