### ISSUE TITLE
Support use zookeeper as peer discovery

### ISSUE THREAD

**Issue by mozillazg** [mailgun/gubernator#21]
First of all, thank you for your work. This project is is so awesome! 👍 

After read documents of Gubernator, I known it can use etcd or kubernetes to discover peers and establish a cluster. Do you have any plan to add "use zookeeper as peer discovery" support in the near future? Thanks!

**Comment by thrawn01** [comment]
No plans for zookeeper, we have not had good experiences running zookeeper in production so I'm not in a hurry to implement support. Pull requests welcome though!
