### ISSUE TITLE
Peering authentication

### ISSUE THREAD

**Issue by japem** [mailgun/gubernator#226]
Is there any way to authenticate peering requests? As far as I can tell, there is to be no way to hook into the gRPC client created by the peering instance to add any sort of credentials to the peering request object, nor is there support for mTLS.

How is a use case that considers rate limit statuses to be sensitive supposed to make use of the peering feature?

**Comment by Baliedge** [comment]
This repo will soon be moving to https://github.com/gubernator-io/gubernator/.  I recommend creating an issue there.
