### ISSUE TITLE
Ability to reset the rate limit for a key

### ISSUE THREAD

**Issue by joshbohde** [mailgun/gubernator#29]
I have a use case where we'd like to reset the rate limit for a key to 0. I'm currently emulating this by doing a 0 hit request to check the current value, and then doing another request to subtract this. 

This method isn't safe under concurrency, however, since concurrent attempts at this could subtract it multiple times.

**Comment by thrawn01** [comment]
This is an interesting use case!  I would like to keep the ability to subtract from a rate limit, but you make a valid point. I think we can add a new `Behaviour` flag to reset the remaining regardless of its current value. 

Something like 
```golang
resp, err := client.GetRateLimits(context.Background(), &guber.GetRateLimitsReq{
	Requests: []*guber.RateLimitReq{
		{
			Name:      "test_change_limit",
			UniqueKey: "account:1234",
			Algorithm: tt.Algorithm,
			Duration:  guber.Millisecond * 100,
			Limit:     tt.Limit,
			Behavior:  guber.Behavior_Reset_Remaining,
		},
	},
})
```
Thoughts?

**Comment by joshbohde** [comment]
This looks like it will address our use case. Thanks for looking into it!
