### ISSUE TITLE
Out-of-date container registry image

### ISSUE THREAD

**Issue by jacksontj** [mailgun/gubernator#31]
The easy way to reproduce this is to simply create a ratelimit of 1/s and then send 10/s+ (anything > 1/s should be sufficient). Once this is done the ratelimit will have a single succes (UNDER_LIMIT) then all subsequent requests will fail.

**Comment by jacksontj** [comment]
it appears this was fixed in https://github.com/mailgun/gubernator/commit/db3a6f0da239746635658f1d53224b0a13ae909c#diff-9c1a840a58a452f6b783331c11026b5e but the container image wasn't updated on https://hub.docker.com/r/thrawn01/gubernator -- is there another registry I should be pulling from?

**Comment by thrawn01** [comment]
Sorry it's been a very busy holiday season, I've updated the docker image to the latest 0.7.1 release.
