### ISSUE TITLE
Feature RFC: Sliding Window Rate Limiting

### ISSUE THREAD

**Issue by falschparker82** [mailgun/gubernator#35]
Hi team,

thanks for all the great work so far, the design of gubernator looks rock solid and sensible so far! 

We're currently evaluating the project for a number of use cases (Golang / Python shop here as well), and so far I see the Token Bucket and Leaky Bucket algorithms already implemented, both of them having some drawbacks.

Therefore, we wanted to ask if there is interest in having a `sliding window` algorithm implemented as well. If the maintainers think this is all of wanted, feasible and the algorithm is reasonably pluggable, we'd be happy to contribute in getting this implemented, by the means of reviews, sponsorship and/or investing own development resources.

Some background, citing from https://konghq.com/blog/how-to-design-a-scalable-rate-limiting-algorithm/ :

> Sliding Window
> 
> This is a hybrid approach that combines the low processing cost of the fixed window algorithm, and the improved boundary conditions of the sliding log. Like the fixed window algorithm, we track a counter for each fixed window. Next, we account for a weighted value of the previous window’s request rate based on the current timestamp to smooth out bursts of traffic. For example, if the current window is 25% through, then we weight the previous window’s count by 75%. The relatively small number of data points needed to track per key allows us to scale and distribute across large clusters.
> 
> We recommend the sliding window approach because it gives the flexibility to scale rate limiting with good performance. The rate windows are an intuitive way she to present rate limit data to API consumers. It also avoids the starvation problem of leaky bucket, and the bursting problems of fixed window implementations.

**Comment by thrawn01** [comment]
Sorry it took so long for me to respond, it's been a busy holiday season! Thanks for your interest! I would be very interested in collaborating with you on a sliding window algorithm! What changes outside of implementing a `slidingWindow()` method in `algorithms.go` do you think you might need? 

From my reading of the algorithm it should fairly simple to store the windows in a `SlidingWindowItem` struct. https://github.com/mailgun/gubernator/blob/3225e16a0a69a8aaac8dfb3e7651a9ff9b16131f/store.go#L11

I think this would fit nicely into gubernator. Thoughts?

**Comment by thrawn01** [comment]
Closing due to age
