### ISSUE TITLE
Feature: optional metric on current throttling status per key

### ISSUE THREAD

**Issue by aligthart** [mailgun/gubernator#43]
We are evaluating gubernator and so far so good.
In our business case we manage the number of tenants on our platform and the number of tenants is not too large. We can set throttling limits for each tenant but would also like to warn a tenant before going over their limit.

As gubernator is already exposing prometheus metrics, it would be nice if there would be metrics like:

 * "name" + "unique_key" => "limit"
 * "name" + "unique_key" => "remaining"
OR
* "name" + "unique_key" => "percentage used"

Based on that an alert manager could send alerts to tenants when reaching a certain percentage.

I can imagine this metric only makes sense in certain business cases and to avoid consuming too much memory I guess when implemented it should be optional.

**Comment by thrawn01** [comment]
You could do this yourself by querying gubernator API and emitting an alert when a customer gets close to a limit. You would need to know which keys to look for. We do something similar here at mailgun we keep a list of currently active customers and we query the API to see if they are getting close to the their quotas.
