### ISSUE TITLE
update mode dependency on k8.io/client-go package

### ISSUE THREAD

**Issue by nipak** [mailgun/gubernator#53]
W0508 18:04:04.833010       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Endpoints ended with: too old resource version: 38203386 (38203932)

**Comment by thrawn01** [comment]
Need to understand where and why this error is occuring in order to fix.

**Comment by denkyl08** [comment]
@thrawn01  this issue can be closed.
