### ISSUE TITLE
Support TLS for GRPC rate-limiter request interface

### ISSUE THREAD

**Issue by nipak** [mailgun/gubernator#59]
I have patch for GRPC TLS support, but would wait till pull-request for issue #55 is merged as there is some refactoring of TLS support to etcd which can be reused.

**Comment by thrawn01** [comment]
I was going to work on this once #55 is merged, which should be soon. A lot of things changed and I want to make sure TLS is included. Would you mind sharing your PR so I make sure I don't miss anything?
