### ISSUE TITLE
Allow multiple behavior flags in request

### ISSUE THREAD

**Issue by patrick-hallinan** [mailgun/gubernator#62]
When I saw that the behavior "flags" were bit fields I assumed that I could combine them:
```
    // Behavior: no_batching=1, global=2, duration_is_gregorian=4, reset_remaining=8, multi_region=16
    {
        "requests":[{
                "name": "name",
                "unique_key": "key",
                "hits": 1,
                "duration": 60000,
                "limit": 10,
                "behavior": 1 | 2
        }]
    }
```
But I get:
```
{"responses":[{"error":"behavior DURATION_IS_GREGORIAN is set; but `Duration` is not a valid gregorian interval","metadata":{"owner":"gubernator-1:91"}}]}
```
I want to be able to set the behavior in a single request.  If I'm rate limiting something bursty that has a config expiring regularly then I need special handling to make sure that the behavior settings haven't reset.  If I can send the complete behavior in a single request it simplifies the client.

I don't know how hard or easy this would be or if it's desirable within the vision of this project but I could possibly help.

**Comment by thrawn01** [comment]
Behavior has been a flag since v0.8.0 See #41. Might be related to #65 which I've updated to the latest release.
