### ISSUE TITLE
[bug] coreos/etcd with undefined

### ISSUE THREAD

**Issue by SpareShade** [mailgun/gubernator#63]
Gurbernator fails to compile due to the incompatibility in coreos's etcd:

> Looks like etcd is still using an experimental grpc-go API that was marked as deprecated and announced for deletion 6 months ago:

etcd-io/etcd#11931

which is related to
grpc/grpc-go#3180

Apparently 

> v3.4 already has that fix.

**Comment by thrawn01** [comment]
I was unable to duplicate, I'm compiling with 1.13 and 1.14.5. Please re-open if you have further information.
