### ISSUE TITLE
docker-compose.yml is missing etcd service

### ISSUE THREAD

**Issue by SpareShade** [mailgun/gubernator#64]
The current `docker-compose.yaml` (`https://raw.githubusercontent.com/mailgun/gubernator/master/docker-compose.yaml`) is missing the `etcd` service settings.

The `etcd` service used to be:
```yml
  etcd:
    image: quay.io/coreos/etcd:v3.2
    command: >
      /usr/local/bin/etcd
      -name etcd0
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://0.0.0.0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd0=http://0.0.0.0:2380
      -initial-cluster-state new  
```

Also the wording for **"Docker compose"** at `https://hub.docker.com/r/thrawn01/gubernator` perhaps needs to be updated too.

Thanks for the great service!

**Comment by thrawn01** [comment]
I think this is related to #65, with the latest version of gubernator memberlist is used to discover the other peers. I've updated the image and docker-compose now works properly.
