### ISSUE TITLE
Docker hub image needs updating

### ISSUE THREAD

**Issue by mdobosz-isp** [mailgun/gubernator#65]
The [latest](https://hub.docker.com/r/thrawn01/gubernator/tags) image is `0.7.1`, whereas the most recent release is [`0.8.3`](https://github.com/mailgun/gubernator/releases/tag/v0.8.3).

**Comment by thrawn01** [comment]
Thank you for making this issue, The image has been updated. https://hub.docker.com/r/thrawn01/gubernator/tags
