### ISSUE TITLE
Update grpc-gateway module

### ISSUE THREAD

**Issue by smf8** [mailgun/gubernator#95]
Hello and first thank you for your great work.

When I use `gubernator` as a client library I get this warning message: 
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.
```
Since this is a [known issue](https://github.com/golang/protobuf/issues/1104). I guess the problem is [here](https://github.com/mailgun/gubernator/blob/master/go.mod#L9) and as described in the original issue, `grpc-gateway` should be updated to a version later than `v1.14.5`.

**Comment by thrawn01** [comment]
Thank you for reporting this! Updated to latest version of grpc-gateway in #96
