### ISSUE TITLE
Resource usage monitoring

### ISSUE THREAD

**Issue by parsaaes** [mailgun/gubernator#97]
I want to have a monitoring about the usage of resource like CPU and memory. As gubernator is using Prometheus Golang client, I think the easiest way to achieve this is to use the process collector of the client. (https://github.com/prometheus/client_golang/blob/master/prometheus/collectors/process_collector.go)

What do you think about adding this?

**Comment by smf8** [comment]
I agree; it would be great to register default `ProcessCollector` before registering `promRegister` [here](https://github.com/mailgun/gubernator/blob/master/daemon.go#L207) with empty options.

Also, for the sake of performance, you can add this as an option in config.
