### ISSUE TITLE
Active expiration for cache keys

### ISSUE THREAD

**Issue by alter123** [mailgun/gubernator#98]
Currently the expiration of keys is determined passively (i.e. whenever we try to access a particular key having `InvalidAt or ExpireAt < now`). But this effectively mean that a non-accessed may reside in memory forever! which may be a bottleneck for scenario where we limit requests which may not be repeated frequently, and the gubernator node isn't restarted for a longer period of time.

Also, this may possibly make us consider other parameters like `maxmemory` and various eviction policies etc.

Do we've any planned way to mitigate this (or rather it exists already and I missed in case).

**Comment by thrawn01** [comment]
Good question, gubernator uses a [LRU cache](https://www.interviewcake.com/concept/java/lru-cache) which has a maximum number of entries set by `DaemonConfig.CacheSize` and `GUBER_CACHE_SIZE`.  This keeps the cache from growing out of control.
